'use client';

import { memo } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { createPaymentSchema, type CreatePaymentFormData } from '@/domain/validators/payment.validator';
import { useCreatePayment } from '@/hooks/queries/use-payment-queries';
import { ErrorMessage } from '@/components/common/ErrorMessage';
import { ApiError } from '@/domain/types/error.types';
import { Input } from '@/components/common/Input';
import { Button } from '@/components/common/Button';
import { useState, useCallback, useMemo, useEffect } from 'react';
import { generateOrderNo } from '@/lib/utils';

export const CreatePaymentForm = memo(() => {
  const { mutate: createPayment, isPending: loading, error } = useCreatePayment();
  const [success, setSuccess] = useState(false);

  const autoGeneratedOrderNo = useMemo(() => generateOrderNo(), []);

  const defaultValues = useMemo(
    () => ({
      orderNo: autoGeneratedOrderNo,
      amountTaxFree: 0,
    }),
    [autoGeneratedOrderNo]
  );

  const {
    register,
    handleSubmit,
    setValue,
    watch,
    formState: { errors },
  } = useForm<CreatePaymentFormData>({
    resolver: zodResolver(createPaymentSchema),
    defaultValues,
  });

  useEffect(() => {
    setValue('orderNo', autoGeneratedOrderNo);
  }, [autoGeneratedOrderNo, setValue]);

  useEffect(() => {
    setValue('amountTaxFree', 0);
  }, [setValue]);

  const orderNoValue = watch('orderNo');
  const amountTaxFreeValue = watch('amountTaxFree');

  useEffect(() => {
    if (orderNoValue !== autoGeneratedOrderNo) {
      setValue('orderNo', autoGeneratedOrderNo);
    }
  }, [orderNoValue, autoGeneratedOrderNo, setValue]);

  useEffect(() => {
    if (amountTaxFreeValue !== 0) {
      setValue('amountTaxFree', 0);
    }
  }, [amountTaxFreeValue, setValue]);

  const onSubmit = useCallback(
    (data: CreatePaymentFormData) => {
      const baseUrl = typeof window !== 'undefined' ? window.location.origin : '';
      const retUrl = `${baseUrl}/payments/success?orderNo=${autoGeneratedOrderNo}`;
      const retCancelUrl = `${baseUrl}/payments/cancel?orderNo=${autoGeneratedOrderNo}`;

      createPayment(
        {
          ...data,
          amountTaxFree: data.amountTaxFree ?? 0,
          retUrl,
          retCancelUrl,
          expiredTime:
            data.expiredTime ||
            new Date(Date.now() + 3600000).toISOString(),
        },
        {
          onSuccess: (response) => {
            if (response.checkoutPage) {
              window.location.href = response.checkoutPage;
            } else {
              setSuccess(true);
            }
          },
        }
      );
    },
    [createPayment, autoGeneratedOrderNo]
  );

  if (success) {
    return (
      <div className="bg-green-50 border border-green-200 text-green-700 px-4 py-3 rounded">
        <p className="font-medium">결제가 생성되었습니다.</p>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
      <Input
        label="주문번호"
        type="text"
        {...register('orderNo', {
          onChange: (e) => {
            e.target.value = autoGeneratedOrderNo;
            setValue('orderNo', autoGeneratedOrderNo);
          },
        })}
        error={errors.orderNo?.message}
        disabled={true}
        readOnly
        helperText="자동 생성됩니다"
      />

      <Input
        label="상품 명"
        type="text"
        {...register('productDesc')}
        error={errors.productDesc?.message}
        disabled={loading}
      />

      <Input
        label="결제 금액"
        type="number"
        {...register('amount', { valueAsNumber: true })}
        error={errors.amount?.message}
        disabled={loading}
      />

      <Input
        label="비과세 금액"
        type="number"
        {...register('amountTaxFree', { 
          valueAsNumber: true,
          onChange: (e) => {
            e.target.value = '0';
            setValue('amountTaxFree', 0);
          },
        })}
        error={errors.amountTaxFree?.message}
        disabled={true}
        readOnly
        helperText="고정값: 0"
      />

      <ErrorMessage
        error={
          error instanceof ApiError
            ? error
            : error
              ? new ApiError('UNKNOWN_ERROR', 500, '알 수 없는 오류가 발생했습니다.')
              : null
        }
      />

      <Button
        type="submit"
        disabled={loading}
        loading={loading}
        className="w-full"
      >
        결제 생성
      </Button>
    </form>
  );
});

CreatePaymentForm.displayName = 'CreatePaymentForm';
