global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: auth-server
    metrics_path: /auth/actuator/prometheus
    static_configs:
      - targets: ["auth-server:9000"]
        labels:
          application: auth-server

  - job_name: user-portal
    metrics_path: /user/actuator/prometheus
    static_configs:
      - targets: ["user-portal:8081"]
        labels:
          application: user-portal

  - job_name: admin-portal
    metrics_path: /admin/actuator/prometheus
    static_configs:
      - targets: ["admin-portal:8082"]
        labels:
          application: admin-portal

  - job_name: member-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["member-service:8083"]
        labels:
          application: member-service
