package com.sleekydz86.oidstudy.global.config;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Slf4j
@Component
public class DatabaseSchemaInitializer implements ApplicationRunner {

    private final JdbcTemplate jdbcTemplate;

    public DatabaseSchemaInitializer(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(ApplicationArguments args) {
        ensureTable(
                "APP_USER",
                """
                create table app_user (
                    user_id number generated by default on null as identity primary key,
                    provider varchar2(40 char) not null,
                    provider_user_id varchar2(255 char) not null,
                    login_id varchar2(40 char),
                    email varchar2(255 char),
                    display_name varchar2(100 char),
                    nickname varchar2(100 char),
                    contact_number varchar2(30 char),
                    profile_image_url varchar2(500 char),
                    status varchar2(30 char) not null,
                    terms_agreed_at timestamp,
                    created_at timestamp not null,
                    updated_at timestamp not null,
                    last_login_at timestamp,
                    approved_at timestamp,
                    approved_by number,
                    withdrawn_at timestamp,
                    withdrawal_reason varchar2(500 char),
                    constraint uk_app_user_provider unique (provider, provider_user_id),
                    constraint uk_app_user_login_id unique (login_id),
                    constraint fk_app_user_approved_by foreign key (approved_by) references app_user(user_id)
                )
                """
        );

        ensureTable(
                "APP_ROLE",
                """
                create table app_role (
                    role_id number generated by default on null as identity primary key,
                    role_code varchar2(50 char) not null,
                    role_name varchar2(100 char) not null,
                    created_at timestamp not null,
                    constraint uk_app_role_code unique (role_code)
                )
                """
        );

        ensureTable(
                "APP_USER_ROLE",
                """
                create table app_user_role (
                    user_id number not null,
                    role_id number not null,
                    created_at timestamp not null,
                    constraint pk_app_user_role primary key (user_id, role_id),
                    constraint fk_app_user_role_user foreign key (user_id) references app_user(user_id),
                    constraint fk_app_user_role_role foreign key (role_id) references app_role(role_id)
                )
                """
        );

        ensureTable(
                "ADMIN_NOTIFICATION",
                """
                create table admin_notification (
                    notification_id number generated by default on null as identity primary key,
                    category varchar2(50 char) not null,
                    title varchar2(255 char) not null,
                    message varchar2(1000 char) not null,
                    target_user_id number,
                    created_at timestamp not null,
                    read_at timestamp
                )
                """
        );
    }

    private void ensureTable(String tableName, String ddl) {
        Integer count = jdbcTemplate.queryForObject(
                "select count(*) from user_tables where table_name = ?",
                Integer.class,
                tableName
        );
        if (count != null && count > 0) {
            return;
        }

        jdbcTemplate.execute(ddl);
        log.info("누락된 테이블을 생성했습니다: {}", tableName);
    }
}
