spring.application.name=catalog-command-service
server.port=8081
app.service-name=catalog-command-service

spring.datasource.url=jdbc:postgresql://localhost:5432/catalogflow
spring.datasource.username=catalogflow
spring.datasource.password=catalogflow
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.format_sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.sql.init.mode=never

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true

app.messaging.exchange-events=catalog.events
app.messaging.exchange-dead-letter=catalog.dlx
app.messaging.queue-enrichment-results=catalog-command.enrichment-results
app.messaging.routing-key-prefix=catalog.product
app.outbox.publish-batch-size=100
app.outbox.publisher-enabled=true
