spring.application.name=catalog-command-service
server.port=8081
app.service-name=catalog-command-service

spring.datasource.url=jdbc:postgresql://localhost:5432/catalogflow
spring.datasource.username=catalogflow
spring.datasource.password=catalogflow
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.format_sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.sql.init.mode=never

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true

app.messaging.exchange-events=catalog.events
app.messaging.exchange-commands=catalog.commands
app.messaging.exchange-dead-letter=catalog.dlx
app.messaging.queue-query-product-events=catalog-query.product-events
app.messaging.queue-query-product-events-retry=catalog-query.product-events.retry
app.messaging.queue-ai-enrichment-requests=ai-worker.enrichment-requests
app.messaging.queue-enrichment-results=catalog-command.enrichment-results
app.messaging.queue-batch-retry=catalog-batch.retry
app.messaging.queue-dead-letter=catalog.dead-letter
app.messaging.routing-key-prefix=catalog.product
app.messaging.consumer-prefetch=10
app.messaging.retry-max-attempts=3
app.messaging.retry-initial-delay-ms=3000
app.messaging.retry-multiplier=2.0
app.messaging.publisher-confirm-timeout-ms=5000
app.outbox.publish-batch-size=100
app.outbox.publisher-enabled=true

app.messaging.consumer-enabled=true

app.storage.provider=s3
app.storage.bucket=catalogflow-images
app.storage.region=ap-northeast-2
app.storage.endpoint=http://localhost:4566
app.storage.access-key=test
app.storage.secret-key=test
app.storage.path-style-access=true
app.storage.max-file-size-bytes=10485760
app.storage.presign-duration-seconds=900
app.storage.allowed-content-types=image/jpeg,image/png,image/webp,image/gif

app.security.enabled=true
app.security.audience=catalogflow-api
app.security.issuer-uri=http://localhost:8080/realms/catalogflow
app.security.jwt-decoder-mode=issuer

springdoc.api-docs.path=/api/v1/system/api-docs
springdoc.swagger-ui.path=/api/v1/system/docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.url=/api/v1/system/api-docs
springdoc.paths-to-match=/api/**

app.network.public-access-enabled=true
app.network.main-service-port=8081
app.network.main-service-name=catalog-command-service
app.network.actuator-access-enabled=true

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=when_authorized
management.metrics.tags.application=${spring.application.name}
management.observations.key-values.service=${spring.application.name}
